<?php
/**
 * Rocket Web
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category  RocketWeb
 * @package   RocketWeb_CrossOrigin
 * @copyright Copyright (c) 2016-2017 RocketWeb (http://rocketweb.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author    Rocket Web Inc.
 */
?>
<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<?php
/** @var \RocketWeb\CrossOrigin\Helper\Data $_helper */
$_helper = $this->helper('RocketWeb\CrossOrigin\Helper\Data');
$urls = $_helper->getUrlMap();
?>
<script>
if (!window.rocketWeb) {
    window.rocketWeb = {}
}
window.rocketWeb.crossOriginUrls = <?php echo json_encode($urls); ?>;
</script>
